[project]
name = "funlog-tau"
version = "0.1.8"
description = "funlog"
readme = "README.md"
requires-python = ">=3.5"
dependencies = [ "loguru>=0.7.3",]
[[project.authors]]
name = "niuliangtao"
email = "farfarfun@qq.com"

[tool.setuptools]
license-files = []
