[project]
name = "nltlog"
version = "1.0.11"
description = "nltlog"
readme = "README.md"
requires-python = ">=3.6"
dependencies = [ "loguru>=0.7.3",]
[[project.authors]]
name = "niuliangtao"
email = "farfarfun@qq.com"

[tool.setuptools]
license-files = []
